### PR TITLE
Opt out of copyright entirely

### PR DESCRIPTION
**Pull request by Flaiker**
Lose all rights to the code by dedicating it to public domain!
http://unlicense.org/

@DerKaito @oOAbaddonOo @Aloewen @haenschenklein what are your opinions regarding this change?

### CODE REVIEW

**Comment by Paretos** [comment]
For my application , a license is necessary.

**Comment by Flaiker** [comment]
Well there's none currently...

**Comment by haenschenklein** [comment]
No license? Or no application?

**Comment by Flaiker** [comment]
No license. By not having a license you are currently literally under [no-license] (http://choosealicense.com/no-license/) which means the default copyright laws apply with the addition of GitHubs terms of service (everyone is allowed to fork / view).

**Pull request closed without merging**
