### PR TITLE
Delete everything

### PR DESCRIPTION
**Pull request by Flaiker**

### CODE REVIEW

**Comment by Paretos** [comment]
Not productive enought

**Comment by DerKaito** [comment]
I like the changes

**Comment by Flaiker** [comment]
*enough

**Comment by Flaiker** [comment]
Thanks @DerKaito

**Comment by DerKaito** [comment]
No Problem @Flaiker

**Comment by Flaiker** [comment]
I suggest we continue this project over at my namespace, this maintainer doesnt seem to like the changes...

**Pull request closed without merging**
